package cpfandcnpj

// CNPJVersion defines which CNPJ standard should be generated.
type CNPJVersion string

const (
	// CNPJV1 generates the numeric CNPJ standard with 14 digits.
	CNPJV1 CNPJVersion = "v1"

	// CNPJV2 generates the alphanumeric CNPJ standard with 12 base characters
	// and 2 numeric check digits.
	CNPJV2 CNPJVersion = "v2"
)

func (cnpjVersion CNPJVersion) isValid() bool {
	switch cnpjVersion {
	case CNPJV1, CNPJV2:
		return true
	default:
		return false
	}
}

// GenerateCNPJ generates a valid CNPJ according to the selected
// official standard.
//
// There are currently two supported CNPJ standards:
//
// 1️⃣ Version 1 — Numeric CNPJ (legacy / current standard)
//   - Format: 14 numeric digits
//   - Example: 12.345.678/0001-95
//   - Still widely used and accepted
//   - Generated by GenerateCNPJV1
//
// 2️⃣ Version 2 — Alphanumeric CNPJ (new official standard)
//   - Format: 12 alphanumeric characters + 2 numeric check digits
//   - Example: 12.ABC.345/01DE-35
//   - Introduced by Receita Federal / SERPRO
//   - Uses ASCII-based calculation and Modulo 11
//   - Generated by GenerateCNPJV2
//
// Parameters:
//
//   - cnpjVersion:
//     Defines which CNPJ standard should be used:
//   - "v1" → Numeric CNPJ (default / legacy standard)
//   - "v2" → Alphanumeric CNPJ (new official standard)
//   - Default is "v1"
//
// Returns:
//
//   - A valid CNPJ Bytes value according to the selected version.
//
// Examples:
//
//	GenerateCNPJ("")          // Generates numeric CNPJ (version 1)
//	GenerateCNPJ(CNPJV1)      // Same as above (version 1)
//	GenerateCNPJ(CNPJV2)      // Generates alphanumeric CNPJ (version 2)
func GenerateCNPJ(cnpjVersion CNPJVersion) Bytes {
	if cnpjVersion == "" || !cnpjVersion.isValid() {
		cnpjVersion = CNPJV1
	}

	if cnpjVersion == CNPJV2 {
		return GenerateCNPJV2()
	}

	return GenerateCNPJV1()
}
