// Feito por: Logan

import generateCnpj1 from "./cnpjGenerator1";
import generateCnpj2 from "./cnpjGenerator2";

export type CnpjVersion = "v1" | "v2";

export const CNPJ_VERSIONS: Record<string, CnpjVersion> = {
  V1: "v1",
  V2: "v2",
};

/**
 * Generates a valid CNPJ according to the selected official standard.
 *
 * There are currently two supported CNPJ standards:
 *
 * 1️⃣ Version 1 — Numeric CNPJ (legacy / current standard)
 * - Format: 14 numeric digits
 * - Example: 12.345.678/0001-95
 * - Still widely used and accepted
 * - Generated by `generateCnpj1`
 *
 * 2️⃣ Version 2 — Alphanumeric CNPJ (new official standard)
 * - Format: 12 alphanumeric characters + 2 numeric check digits
 * - Example: 12.ABC.345/01DE-35
 * - Introduced by Receita Federal / SERPRO
 * - Uses ASCII-based calculation and Modulo 11
 * - Generated by `generateCnpj2`
 *
 * @param cnpjVersion
 * Defines which CNPJ standard should be used:
 * - `"v1"` → Numeric CNPJ (default / legacy standard)
 * - `"v2"` → Alphanumeric CNPJ (new official standard)
 * - Default is `"v1"`
 *
 * @returns A valid CNPJ string according to the selected version.
 *
 * @example
 * generateValidCNPJ();        // Generates numeric CNPJ (version 1)
 * generateValidCNPJ("v1");       // Same as above
 * generateValidCNPJ("v2");       // Generates alphanumeric CNPJ
 */
function generateValidCNPJ(cnpjVersion: CnpjVersion = "v1"): string {
  if (cnpjVersion === "v2") {
    return generateCnpj2();
  }

  return generateCnpj1();
}

export default generateValidCNPJ;
